---
- name: Build and Deploy Bhushan PhotoQuest
  hosts: localhost
  connection: local
  vars:
    docker_front_repo: "nagabhushan9676/b-photoquest-front"
    docker_back_repo: "nagabhushan9676/b-photoquest"

  # tasks:
  #   ### DOCKER IMAGE BUILD & PUSH ###
  #   - name: Build/push frontend Docker image
  #     docker_image:
  #       name: "{{ docker_front_repo }}"
  #       tag: "{{ build_number }}"
  #       repository: "https://github.com/NagaBhushan9676/bhushan_PhotoQuest.git"
  #       source: build
  #       push: yes
  #       build:
  #         pull: yes
  #         path: .
  #         context_subdir: "searchI"   # Path to frontend Dockerfile in repo
  tasks:
    ### DOCKER IMAGE BUILD & PUSH ###
    # - name: Build/push frontend Docker image
    #   shell: |
    #     docker build -t {{ docker_front_repo }}:{{ build_number }} -f searchI/Dockerfile ./searchI
    #     docker push {{ docker_front_repo }}:{{ build_number }}
    #   args:
    #     chdir: "{{ playbook_dir }}/.."

    - name: Build/push backend Docker image
      shell: |
        docker build -t {{ docker_back_repo }}:{{ build_number }} -f backend/Dockerfile ./backend
        docker push {{ docker_back_repo }}:{{ build_number }}
      args:
        chdir: "{{ playbook_dir }}/.."
        
    # - name: Build/push backend Docker image
    #   docker_image:
    #     name: "{{ docker_back_repo }}"
    #     tag: "{{ build_number }}"
    #     repository: "https://github.com/NagaBhushan9676/bhushan_PhotoQuest.git"
    #     source: build
    #     push: yes
    #     build:
    #       pull: yes
    #       path: .
    #       context_subdir: "backend"   # Path to backend Dockerfile in repo

    ### ARGOCD DEPLOYMENT ###
    # - name: Update frontend image tag in ArgoCD
    #   command: >
    #     argocd app set frontend --parameter image.tag={{ build_number }}

    # - name: Sync frontend app in ArgoCD
    #   command: argocd app sync frontend-{{ target_env }}

    - name: Login to argocd
      shell: |
        argocd login 10.255.255.254:50892 --username admin --password Nag@9494 --insecure

    - name: Update backend image tag in ArgoCD
      command: >
        argocd app set backend --parameter image.tag=1.0

    - name: Sync backend app in ArgoCD
      command: argocd app sync backend-{{ target_env }}