---
- name: Build and Deploy Bhushan photoQuest
  hosts: all
  vars:
    docker_front_repo: "nagabhushan9676/b-photoquest-front"
    docker_back_repo: "nagabhushan9676/b-photoquest"

  tasks:
## Clone the Repos
    - name: Clone monorepo
      git:
        repo: "{{ frontend_repo }}"
        dest: "../build/source"
        version: main
        force: yes

    - name: Copy frontend (searchI) to build/frontend
      copy:
        src: "../build/source/searchI/"
        dest: "../build/frontend/"
        remote_src: yes

    - name: Copy backend to build/backend
      copy:
        src: "../build/source/backend/"
        dest: "../build/backend/"
        remote_src: yes
## Build APP
    - name: Install Node.js dependencies
      command: "npm install"
      args:
        chdir: "../build/backend"
    - name: Install Frontend dependencies
      command: "npm install && npm run build"
      args:
        chdir: "../build/frontend"
## Build Docker Image
    - name: Build Frontend Docker image
      docker_image:
        path: "../build/frontend"
        name: "{{ docker_front_repo }}"
        tag: "{{ docker_image_tag }}"
        push: yes
        source: build
        build:
          pull: yes
      
    - name: Build Backend Docker image
      docker_image:
        path: "../build/backend"
        name: "{{ docker_back_repo }}"
        tag: "{{ docker_image_tag }}"
        push: yes
        source: build
        build:
          pull: yes
## Argocd Deploy
    - name: Update ArgoCD for frontend
      command: >
        argocd app set frontend --parameter image.tag={{ docker_image_tag }}
    - name: Sync ArgoCD for frontend
      command: argocd app sync frontend-{{ target_env }}
      
    - name:  Update ArgoCD for backend
      command: >
        argocd app set backend --parameter image.tag={{ docker_image_tag }} 
        
    - name: Sync ArgoCD for backend
      command: argocd app sync backend-{{ target_env }}